import type { AgentHandler } from '@treeseed/sdk/utils/agents/runtime-types';
import {
	parseAgentMessagePayload,
	serializeAgentMessagePayload,
} from '@treeseed/sdk/utils/agents/contracts/messages';

interface ArchitectInputs {
	objectiveId: string | null;
	reason: string | null;
}

interface ArchitectResult extends ArchitectInputs {
	knowledgeSlug: string | null;
}

export const architectHandler: AgentHandler<ArchitectInputs, ArchitectResult> = {
	kind: 'architect',
	async resolveInputs(context) {
		if (!context.trigger.message) {
			throw new Error('Architect requires a claimed message trigger.');
		}
		const payload = parseAgentMessagePayload(
			'objective_priority_updated',
			String(context.trigger.message.payloadJson),
		);
		return {
			objectiveId: payload.objectiveId,
			reason: payload.reason,
		};
	},
	async execute(context, inputs) {
		if (!inputs.objectiveId) {
			return {
				...inputs,
				knowledgeSlug: null,
			};
		}

		const knowledgeSlug = `architecture/agent-mvp/${inputs.objectiveId}-${context.runId}`;
		await context.sdk.create({
			model: 'knowledge',
			data: {
				slug: knowledgeSlug,
				title: `Architecture update for ${inputs.objectiveId}`,
				body: [
					'# Architecture Update',
					'',
					`Objective: ${inputs.objectiveId}`,
					`Reason: ${inputs.reason ?? 'not provided'}`,
					`Run: ${context.runId}`,
					'',
					'This knowledge entry was generated by the MVP architecture handler.',
				].join('\n'),
				tags: ['agent', 'architecture', 'mvp'],
				branchPrefix: context.agent.execution.branchPrefix,
			},
		});

		return {
			...inputs,
			knowledgeSlug,
		};
	},
	async emitOutputs(context, result) {
		if (!result.objectiveId || !result.knowledgeSlug) {
			return {
				status: 'waiting',
				summary: 'Architect found no objective to process.',
			};
		}

		await context.sdk.createMessage({
			type: 'architecture_updated',
			payload: serializeAgentMessagePayload('architecture_updated', {
				objectiveId: result.objectiveId,
				knowledgeId: result.knowledgeSlug,
				architectRunId: context.runId,
			}),
		});
		return {
			status: 'completed',
			summary: `Architect created knowledge ${result.knowledgeSlug}.`,
		};
	},
};
